### ISSUE TITLE
Adicionar novo STATUS "Arquivado" no banco de dados

### ISSUE THREAD

**Issue by FelipeDH9** [GabrielTurri/ac-smart#1]
Precisa adicionar um novo status 'ARQUIVADO' na tabela ATIVIDADE_COMPLEMENTAR

**Comment by victor-san3** [comment]
Alteração na coluna STATUS conforme código abaixo:

`ALTER TABLE atividade_complementar
MODIFY COLUMN status ENUM('Aprovado', 'Reprovado', 'Pendente', 'Arquivado') DEFAULT 'Pendente';`
