### ISSUE TITLE
adicionar campo 'cod_atividade' na tabela 'observacao_atividade'

### ISSUE THREAD

**Issue by FelipeDH9** [GabrielTurri/ac-smart#2]
Precisa tirar o campo 'cod_observacao_atividade' da tabela 'atividade_complementar', e adicionar o campo 'cod_atividade' na tabela 'observacao_atividade'. Do jeito que está agora, a atividade só pode ter uma observação salva, quando o  campo 'cod_observacao_atividade' da tabela 'atividade_complementar' for atualizado, a observação perderá sua rastreabilidade.

**Comment by victor-san3** [comment]
Adequação implementada:

`ALTER TABLE atividade_complementar
DROP FOREIGN KEY fk_cod_observacao_atividade;
`
`ALTER TABLE atividade_complementar
DROP COLUMN cod_observacao_atividade;
`
`ALTER TABLE observacao_atividade
ADD COLUMN cod_atividade INT,
ADD FOREIGN KEY (cod_atividade) REFERENCES atividade_complementar(cod_atividade);
`
